name: monitoring
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
    - 3000:3000
  influx:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - /opt/influx_volume:/var/lib/influxdb2
    depends_on:
      - grafana
